--- 
env: 
  global: 
  - PUBLISHER_LOGIN=seteam
  - secure: |-
      hssdKoiipW9dayQBH8jqDzVX+45CZcWgNrgWAeX2shEL1yHuip05yBe6fJtW
      AqgWVw7YLWbwquL5IbhEVGUNXto+fAlYRIe9aaF09Dw/9oBZoNZKflFLVn7J
      3texD8xreIUdyQktpbH1YLd9lk6RXAHQkWNzLmAe3P7t89Xg4dg=
script: 
- git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng
- .forge-releng/publish
language: ruby
branches: 
  only: 
  - master
